name: Cactus Code Website

collections:
  thorndocs:
    output: true
  arrangementdocs:
    output: true

liquid:
  error_mode: strict # or lax or warn

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      sidebar: "media/news/recent.html"
      nrecentnewsitems: 10
