name: Cactus Code Website
# fixes /assets/css/style.css showing up. See https://github.com/jekyll/jekyll/issues/7478
theme: null

collections:
  thorndocs:
    output: true
  arrangementdocs:
    output: true

liquid:
  error_mode: strict # or lax or warn

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      sidebar: "media/news/recent.html"
      nrecentnewsitems: 10
      release_branch: "Cactus_4.8.0"
  -
    scope:
      path: "media/news"
    values:
      sitemap_exclude: true
  -
    scope:
      path: "global/errors"
    values:
      sitemap_exclude: true
      base_is_absolute: true
      permalink: /:basename:output_ext
